# Generated by Django 5.0.6 on 2024-06-19 08:46

import core.utils.defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default=core.utils.defaults.guid_factory, editable=False, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('host', models.URLField(blank=True, null=True)),
                ('service_name', models.CharField(max_length=100)),
                ('secret', models.CharField(db_index=True, default=core.utils.defaults.guid_factory, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
